[package]
name = "erc20"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
contract = { package = "casper-contract", version="4.0.0" }
types = { package = "casper-types", version="4.0.1" }
hex = "0.4.3"

[[bin]]
name = "erc20"
path = "src/main.rs"
bench = false
doctest = false
test = false

[features]
default = ["contract/std", "types/std"]
